FROM ubuntu:18.04
ARG numberOfCores

COPY ext/01_nodoc /etc/dpkg/dpkg.cfg.d/01_nodoc 

RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        software-properties-common \
        coreutils \
        locales \
        python3-dev  \
        libnss-db \
        libzmq3-dev \
        python3-zmq \
        protobuf-compiler \
        libprotobuf-dev \
        build-essential \
        scons \
        libssl-dev \
        wget \
	curl \
        unzip \
        python3-pip \
        python3-tk \
        libpcre3-dev && \
    wget prdownloads.sourceforge.net/swig/swig-2.0.4.tar.gz && \
    tar zxf swig-2.0.4.tar.gz && \
    (cd swig-2.0.4 && ./configure --prefix=/usr && make && make install) && \
    rm -rf swig-2.0.4 swig-2.0.4.tar.gz 
RUN apt-get -y install cython3 libcurl4-openssl-dev

RUN python3.6 -m pip install --upgrade pip setuptools wheel

RUN pip install numpy scipy pandas spacy nltk scikit-learn statsmodels pyexasol

# Load language models
RUN python3.6 -m spacy download en_core_web_md
RUN python3.6 -c 'import nltk; nltk.download("vader_lexicon")'

RUN apt-get --yes  remove python3-pycurl
RUN python3.6 -m pip install --ignore-installed pycurl
RUN locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 && \
    apt-get -y clean && \
    apt-get -y autoremove && \
    ldconfig
RUN addgroup --gid 1000 exasolution
RUN adduser --disabled-login --uid 1000 --gid 1000 exasolution

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

